// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.24.4
// source: proto/edge/forward.proto

package forward

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForwardPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *ForwardPayload) Reset() {
	*x = ForwardPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_edge_forward_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForwardPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardPayload) ProtoMessage() {}

func (x *ForwardPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_edge_forward_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardPayload.ProtoReflect.Descriptor instead.
func (*ForwardPayload) Descriptor() ([]byte, []int) {
	return file_proto_edge_forward_proto_rawDescGZIP(), []int{0}
}

func (x *ForwardPayload) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ForwardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ForwardResponse) Reset() {
	*x = ForwardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_edge_forward_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardResponse) ProtoMessage() {}

func (x *ForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_edge_forward_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardResponse.ProtoReflect.Descriptor instead.
func (*ForwardResponse) Descriptor() ([]byte, []int) {
	return file_proto_edge_forward_proto_rawDescGZIP(), []int{1}
}

var File_proto_edge_forward_proto protoreflect.FileDescriptor

var file_proto_edge_forward_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x64, 0x67, 0x65, 0x2f, 0x66, 0x6f, 0x72,
	0x77, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x66, 0x6f, 0x72, 0x77,
	0x61, 0x72, 0x64, 0x22, 0x2a, 0x0a, 0x0e, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22,
	0x11, 0x0a, 0x0f, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0x52, 0x0a, 0x0e, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x07, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x12,
	0x17, 0x2e, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72,
	0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x18, 0x2e, 0x66, 0x6f, 0x72, 0x77, 0x61,
	0x72, 0x64, 0x2e, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x42, 0x14, 0x5a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x65, 0x64, 0x67, 0x65, 0x3b, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_edge_forward_proto_rawDescOnce sync.Once
	file_proto_edge_forward_proto_rawDescData = file_proto_edge_forward_proto_rawDesc
)

func file_proto_edge_forward_proto_rawDescGZIP() []byte {
	file_proto_edge_forward_proto_rawDescOnce.Do(func() {
		file_proto_edge_forward_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_edge_forward_proto_rawDescData)
	})
	return file_proto_edge_forward_proto_rawDescData
}

var file_proto_edge_forward_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_edge_forward_proto_goTypes = []interface{}{
	(*ForwardPayload)(nil),  // 0: forward.ForwardPayload
	(*ForwardResponse)(nil), // 1: forward.ForwardResponse
}
var file_proto_edge_forward_proto_depIdxs = []int32{
	0, // 0: forward.ForwardService.Forward:input_type -> forward.ForwardPayload
	1, // 1: forward.ForwardService.Forward:output_type -> forward.ForwardResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_edge_forward_proto_init() }
func file_proto_edge_forward_proto_init() {
	if File_proto_edge_forward_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_edge_forward_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForwardPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_edge_forward_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForwardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_edge_forward_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_edge_forward_proto_goTypes,
		DependencyIndexes: file_proto_edge_forward_proto_depIdxs,
		MessageInfos:      file_proto_edge_forward_proto_msgTypes,
	}.Build()
	File_proto_edge_forward_proto = out.File
	file_proto_edge_forward_proto_rawDesc = nil
	file_proto_edge_forward_proto_goTypes = nil
	file_proto_edge_forward_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ForwardServiceClient is the client API for ForwardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ForwardServiceClient interface {
	Forward(ctx context.Context, opts ...grpc.CallOption) (ForwardService_ForwardClient, error)
}

type forwardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewForwardServiceClient(cc grpc.ClientConnInterface) ForwardServiceClient {
	return &forwardServiceClient{cc}
}

func (c *forwardServiceClient) Forward(ctx context.Context, opts ...grpc.CallOption) (ForwardService_ForwardClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ForwardService_serviceDesc.Streams[0], "/forward.ForwardService/Forward", opts...)
	if err != nil {
		return nil, err
	}
	x := &forwardServiceForwardClient{stream}
	return x, nil
}

type ForwardService_ForwardClient interface {
	Send(*ForwardPayload) error
	CloseAndRecv() (*ForwardResponse, error)
	grpc.ClientStream
}

type forwardServiceForwardClient struct {
	grpc.ClientStream
}

func (x *forwardServiceForwardClient) Send(m *ForwardPayload) error {
	return x.ClientStream.SendMsg(m)
}

func (x *forwardServiceForwardClient) CloseAndRecv() (*ForwardResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ForwardResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ForwardServiceServer is the server API for ForwardService service.
type ForwardServiceServer interface {
	Forward(ForwardService_ForwardServer) error
}

// UnimplementedForwardServiceServer can be embedded to have forward compatible implementations.
type UnimplementedForwardServiceServer struct {
}

func (*UnimplementedForwardServiceServer) Forward(ForwardService_ForwardServer) error {
	return status.Errorf(codes.Unimplemented, "method Forward not implemented")
}

func RegisterForwardServiceServer(s *grpc.Server, srv ForwardServiceServer) {
	s.RegisterService(&_ForwardService_serviceDesc, srv)
}

func _ForwardService_Forward_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ForwardServiceServer).Forward(&forwardServiceForwardServer{stream})
}

type ForwardService_ForwardServer interface {
	SendAndClose(*ForwardResponse) error
	Recv() (*ForwardPayload, error)
	grpc.ServerStream
}

type forwardServiceForwardServer struct {
	grpc.ServerStream
}

func (x *forwardServiceForwardServer) SendAndClose(m *ForwardResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *forwardServiceForwardServer) Recv() (*ForwardPayload, error) {
	m := new(ForwardPayload)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ForwardService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "forward.ForwardService",
	HandlerType: (*ForwardServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Forward",
			Handler:       _ForwardService_Forward_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/edge/forward.proto",
}
