openapi: 3.0.0
info:
  title: SpecPipe Server API
  version: 0.2.0
servers:
  - url: /v0

paths:
  /fm/devices/{devicename}:
    $ref: fm_devices.yaml#/path/fm_devices_devicename
  /fm/devices:
    $ref: fm_devices.yaml#/path/fm_devices
  /iq/devices/{devicename}:
    $ref: iq_devices.yaml#/path/iq_devices_devicename
  /iq/devices:
    $ref: iq_devices.yaml#/path/iq_devices