openapi: 3.0.0
info:
  title: SpecPipe Server API
  version: 0.3.2
servers:
  - url: /v0

paths:
  /fm/devices/{devicename}:
    $ref: devices.yaml#/path/fm_devices_devicename
  /fm/devices:
    $ref: devices.yaml#/path/fm_devices